### ISSUE TITLE
Bot doesn't pick up Twitter links if the link is after a line break

### ISSUE THREAD

**Issue by Delphox** [Dastan21/BDSMbed#3]
![image](https://user-images.githubusercontent.com/5883538/123527502-9d840900-d6b6-11eb-81e4-b598e6e16777.png)

**Comment by Dastan21** [comment]
Yup, fixed in v2.0.0 (29c79611d4f19369763dfa5f4642e779c6e6c193)

**Comment by Delphox** [comment]
Thanks for the big update!

It seems the bot isn't working at all right now for twitter though, I'm guessing the deployment of the new version is incomplete rn?

**Comment by Delphox** [comment]
Oh it was the debug code. It's working now. However twitter gifs are broken now..
