### ISSUE TITLE
Issues with new version on Twitter links

### ISSUE THREAD

**Issue by Delphox** [Dastan21/BDSMbed#4]
Figured it might be better to make a new issue with those.

First, twitter gifs stopped worked altogether, while they worked fine on the previous version:
![PFkMcbn9CT](https://user-images.githubusercontent.com/5883538/123858504-fbecf980-d8f9-11eb-9a38-422e7c828860.gif)
(this is the same gif I used as example on the previous issue)

Second, the bot still posts its temporary message on some image posts, which do embed properly. If there's no way to avoid the message without checking the API first, might be better to just scrap it altogether as it's not very useful and even increase the likelihood of discord API not responding and the message just getting stuck there.
![DB3zGMEtiw](https://user-images.githubusercontent.com/5883538/123858668-2b9c0180-d8fa-11eb-84e2-495404036ac6.gif)
![HwnPBTq0n3](https://user-images.githubusercontent.com/5883538/123861599-c21df200-d8fd-11eb-8271-b53343cd7924.gif)

**Comment by Dastan21** [comment]
Thanks for your feedbacks, fixed in b11ea95
