### ISSUE TITLE
Update 2.2.0 broke the bot when it lacks the Read Message History permission

### ISSUE THREAD

**Issue by Delphox** [Dastan21/BDSMbed#5]
Previous versions worked with the permission denied, which is generally a good idea to have simple response bots with minimum permission scope to minimize risk of the server being retroactively scraped in case their tokens get compromised. I assume its inability to assign a reply broke the response flow.

I think ideally it should have some sort of _else_ condition to just post the message (as it was before) in case it was unable to attach a reply to the post.

**Comment by Dastan21** [comment]
Fixed in 3c13c02. Thx for reporting.
