### ISSUE TITLE
unverified bot on discord

### ISSUE THREAD

**Issue by lilbitofarson** [Dastan21/BDSMbed#6]
![Capturevcv](https://user-images.githubusercontent.com/100814954/156478092-b566d3e6-cfcc-4bd7-bd2e-b46e68332dbf.PNG)

**Comment by Dastan21** [comment]
I'm aware, but the process is kinda annoying and the bot isn't that useful nowadays thanks to [fxtwitter](https://github.com/robinuniverse/TwitFix).
